/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_backaudio_android_driver_LibSerialPort */

#ifndef _Included_com_backaudio_android_driver_LibSerialPort
#define _Included_com_backaudio_android_driver_LibSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_backaudio_android_driver_LibSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_backaudio_android_driver_LibSerialPort_open
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_backaudio_android_driver_LibSerialPort
 * Method:    close
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_com_backaudio_android_driver_LibSerialPort_close
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
